env:
  global:
    - secure: ZS/p8VLRLfg2+QlTeFOYjTvGg+8CEJNuLPq9aL5M5KIVwwfVqS31R4x/vU7QVlMV37TrvY0PqQcvHNGMkFia/pc7mN+V6FJnvAgi9beRR96Q1DB9vvfdRxLyZbDT2YC+vZC4peC2NX2HhcIIZzmlJoNxcnnmaLTra8lf0XUp4TJtzQzT2DCi+8+7AmZmGvpiyi+nwCzErZy0XA5oRtNmwI0yQ1CY9iCmiKiZwknxUi91tSCKg4rYW11e9BuHCbBQ5EA0Holy7jiPMtzfboWq1ryo7y5nWZEwswqmfQi7mgnZpoAt/wCAbN+ljEZwZdRaUshWwBJ1IVwxQRHcvEe3Ymu6VK2CQlfkUMLmZTbjrJRFNBnbjF3w4FFJDyqL38fzxQYIX9RGn0GA0+98D7OsruCNRNEOG8e7qcaevU7aaXTetwJEcoS7i9ET1z9nr5CsVfzqd1WfGLMq2NYJO4AVyNGSACHCuERhoHOVU2/HWWeA49VEvgLU/UjPH986TW6/IGx44wND6QBuWnllT5/wivihuTRHtMQZUDdqfSdRZgNmtg/W4CUiPp1Jzo2GIVCeYewP0kt6CcCSwnJv/5Ji+dmRvLtXtgyOO3mnsUXH4QifJJ7i/k87mtTjADZzVQH2gZ3afYMCAjVy+zI+DAZ1ZfJtCmNEmYmTm8JNXVh4n48=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
