env:
  global:
    - secure: lEtJ7zj1V03ga1aO8KT0Az+wgsBzt1dOcyIe/xHU0Te50sDuV+UKOdKE0UsvnIC4z1V+IzmftFK52Ed0KGFo+Ia514dMbzm+6o16W5pmFVM6i4aJ7ZpOiCCb5bkpAmeNVXqilaKX/rf6p7foXwl95mxliO2TmTcIqYro5drH037XjxeCy08TVpk9zbaPCfQ0/msDhv70b3AvIT75TSR5m+GcQlwKbtoRzZRK2XkKBkFPZ28qLVrq+WtwSAFPg82S+wlPJsFynvOqdPGXcc3XyzCqmS2J9TLdApqkUjAuBE3twcHn/dS2k1WfVSqQWNldBoXbnbZ1/KuXn5cOpY9OhtkK2JigHy4tieDHlI0Uqvh6CBjfnwuuZRQZo/cOVWatsrqGu4HZ+MoY9tRmxGvuZKxLPcIDEfARtLcQRMcuhldSM39EIp3RXwuFz8rDpz4IttQG08hbpEaghK/2daAvG2yncbLrEEEpax7FfyAQQOegU/o/WTev7aFu9jzuzlrn2lYPC/yhHix0ZwE1+n3KojUNO/MnRhxwxqaHK3y6syTgyXqQpz/QxlpLz5b5YS2JPwm8bTbUjy8xS3PflwkUl8q8vj9Y2i/MTxW5YQ8AdV0c19TidYGlD6+M5xPVfwiiKsdQbRDZtysHi2+QVoTZZDq9hzgNe/kGwalja+GekSo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
