env:
  global:
    - secure: kT7c9QHvFo5ODQBTpz93qoY5lEkYrpYeLAqgPtx9zyIqiylKDRX3p1VQPvjy6lZlC+A2Xa1VQFyhoVoLsdkEbolGv+KDy2EYwfBptkUKfa6+Zstvz4uKBOX7sN8DwRO4PMOL+qe7J07s5AImqPY2FyIzbvZO0Zz832io6162mjavOVw75+LFunA/Cgb70r/6+e3UZcOVcyi+1Xo61gqTg2Zlf9Mb199XWl+v2FMMM3pcjk4jyxqTsUYkaY6kxIvwgu50q43/qzCLQPU8I0xj9Edxw2H9YebMmoLHhJvFFfz/IjoELUayS/FP5d9YO4sf8Cabfrye6V+A5Cy/tN/FjGT7uFgkUZCA0Xcnj7xpKQ4MO2JJtv62BSe2ajxSyYGtJyniV8Pu6/RgHA8iYjmysWEYm0kHqlRNzDDsvEXZo7EpCMMl99qWwZPeW7IdQNCeyK+Rt1rTxylGC99SJl6QuWp2BV6/aX4MQivuTQcyPFbs9WNKUilsJgPotMl1N9psPL1H+IPLrUR3uOqz5IzyuXC+eqT2nSCw7WOKHg6yvO2vf8zmIE56xRQDodxjzcbGLgioptK7iRM5j3e/mjv1EPiKp5kVq4ZWcD4I/7qJVj1Wax1mtR30k13QFFeJNTG3SBuooiHPm6wqc1yAU0Om/DYgFNkNRDXPy3sudep/kz8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
