env:
  global:
    - secure: cU9xBxfTejfKsvhTlsve2X8loGRvkOVYvSCFNbFNM1g1pNbWQOeLK9NKFQkkjHB5tzEWSqGBhSST7kXwktyhzOJBMj9NxSYsF0uHy2vaQUH/jnJkMrpWzSprUjvICteKsWQ3CeFGOUohUfhP+szcDwKxmU5kfZCovtf4wmzr1QXJgB5Yv/mxgCr5tv696HEv0AIPqVBiEMXq4LX2uqtL0uDZ2JKZy5X+iCNPMIyLBydRNbY5P/9Z7EyHFEy7n8ioOxmN5gWJBecLpBFX9Wx66jyl7r7Yx+0jaidrwrzG1vCE0gyuvBc9soXadyjopo/RXnRg1avhw3yLNnT5id22z/v3LdgtCOn1vyd1W1bPB6KdXJBI/Dsq8EMyLDtJjhzLnEjZqlB+Riy+XvMe0nqokbDxdlAPdu1Au3EN1XWam4NbKP4TtAGitFcQJH7Ip/poLWVMwVQQyxe+GSGwXkpFwOiVoKEMhJ9ALq16KGFRIYO0/AGgHKO0G+JoNMQcoNUQ0s91h0VGkzHkwDtY9uE05aVYU7Q4OTFhCyrJQhyC0uW+7CAyfzyPHJasfUPmmXd98ucOGd4Io9q0k5vHQAl2PNlLFFsACMBNAcTgVzDOjicdNfx2YsLrmg5QJuKUp1j+HBSK+URQAZp/z6BofhYzxywzieqZjQhS5VWyLJat25o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
