env:
  global:
    - secure: YBx55M8QiXYqdOMB5CB6G10HNzt/axW2QjTPt/AwBGdzYp9gMhDcUNeVO3KOuv34ojyi4W8gpBnwKH+wpKThXFSYV0eT8PQgUQneGx3cbkrPw3vax2BRxTxB/f+Wz6P/q/2iOL7Yng0b3Xd84DL9OYNgDxumMun+ngOMMR/imVK7yzid+Rhqk15cjNy3yONvaTq4OFILVRIPHaBauytdFvdrKvyRJoLo0ya3OKT1pFBNe03ee6g84I/Yy4vp4zFXGZIIfP0kYLTigWkQPRjF60WyrjIQ9ygjxvZ9zdldOgl7SZUSkC8cXD3aYO2DdCgKJxwL4iJ0jt7k6H33kPLsZkNitBKKxfCSxCR4fNpWJjq5ok6+50kraXz3dfQTZm+uDVeazdrP1dWOgu4S70ZLLeMwJvUrcWosJPF1vzrrr0LF2EHovXUK0uZYzDwpC3DEpsIhdC+vFyJHn6eB9CxB8aNcU12efwNsLvJCdTVLGrCmmVfnptVlhhhH/hsKaDpob5wJXN4K7BrAuwBGUGW1PxhJjNiw+7iUaMhz5Pf6y5/081a/Pf6ausrJnXAshE3Yic2od+TN1VbHYNLpO2C8DS1uuMTVb0iREnlnXLfIUXnXKLYNCp5ERVZ0itpTGIWHQUa6hW2QaX90kNEk2D8npSeBVsjnYSNPeHkIHSAZFgc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
