env:
  global:
    - secure: lOUNAsPDMzMOzxtgf7E5iy5mby1YGfTp3NmFanpI7wcY2N4VS4VBuPrq3Rs43/vCHilPZFzoqJwLJ2azM67/T+niMTaTyc7qXl1Radxr4is15+vjMygLY2O1qjD+pSxLGiAddjartJ0Sgdfz9kTFmbg6SJXTmLmsIR0rmxgjXvyaad4mJ67BcbcYBxOgzthcIBOXRmzGw1xDhY9OWqSEpiCQ0eKhQWr6BEZOZa5YTNg5Fk5xzdTf2iNjuBFm88zoFOsUGOcuCMAL4fOR43wNpAw39PC3YU8V7f7rrjfnNJCQMEeZtKJEw7Epr+c7ulACLduFAGqj1H+HFZBIBqPO8q9pQGSNsFYC2oRGoyhv94UIbKGDXB06LITS/71L8YlQ7JQHdTdudYmxuUngog85O2qPazsAYppqIoJge2wK6yVigakTBYqOQhHZgBfDRsDuxb+d4rBxK69lBf5+2G6i1r2ixDndUMdthqMKgKk2oKWG1QzPIwpvHu2zriwoKC/Em1IR7ZWUzxs7Byc/2NNyK47kKFLrskY7zZLH0kq8xqjZqOiJbAdCrQw9C0iqUycD5FqbfQSxx3MRm8w3VeCfeAxOp1NPDOWTu32515u4jXRxqoh6UttKXwraIz28jAHsnhE+YVbPgnAmAuBeZo0brTq+HNe/KnMCun5eWSzBclk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
